version: '3.8'

services:
  app:
    build: .
    container_name: express-api
    ports:
      - "${PORT}:${PORT}"
    volumes:
    - '.:/var/www/html'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - oracle-db

  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=${DB_PASS}
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: always
    shm_size: '1g'
    
volumes:
  oracle-data:
     external: true
